[package]
name = "syntra-proto"
description = "network protocol for lan-mouse"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
num_enum = "0.7.2"
thiserror = "2.0.0"
syntra-input-event.workspace = true
paste = "1.0"
