[workspace]
members = [
    "input-capture",
    "input-emulation",
    "input-event",
    "lan-mouse-ipc",
    "lan-mouse-cli",
    "lan-mouse-proto",
    "lan-mouse-adapter-api",
    "adapters/fuse",
    "adapters/gtk-clipboard",
    "lan-mouse-ui",
    "lan-mouse-history",
]

[package]
name = "lan-mouse"
description = "Software KVM Switch / mouse & keyboard sharing software for Local Area Networks"
version = "0.11.0"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/feschber/lan-mouse"

[profile.release]
codegen-units = 1
lto = "fat"
strip = true
panic = "abort"

[build-dependencies]
shadow-rs = "1.2.0"

[dependencies]
hostname = "0.4"
input-event = { path = "input-event", version = "0.4.0" }
input-emulation = { path = "input-emulation", version = "0.4.0", default-features = false }
input-capture = { path = "input-capture", version = "0.4.0", default-features = false }
lan-mouse-cli = { path = "lan-mouse-cli", version = "0.3.0" }
lan-mouse-ipc = { path = "lan-mouse-ipc", version = "0.4.0" }
lan-mouse-history = { path = "lan-mouse-history", version = "0.1.0" }
lan-mouse-proto = { path = "lan-mouse-proto", version = "0.5.0" }
lan-mouse-adapter-api = { path = "lan-mouse-adapter-api", version = "0.1.0" }
lan-mouse-ui = { path = "lan-mouse-ui", version = "0.1.0", optional = true }
base64 = "0.22"
arboard = { version = "3.6.1", features = ["wayland-data-control"] }
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
shadow-rs = { version = "1.2.0", features = ["metadata"] }
mdns-sd = "0.21.1"

toml = "0.8"
toml_edit = { version = "0.22", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
log = "0.4.20"
env_logger = "0.11.3"
serde_json = "1.0.107"
bincode = "1.3.3"
tokio = { version = "1.32.0", features = [
    "io-util",
    "io-std",
    "macros",
    "net",
    "process",
    "rt",
    "rt-multi-thread",
    "sync",
    "signal",
] }
tokio-util = { version = "0.7", features = ["codec"] }
futures = "0.3.28"
clap = { version = "4.4.11", features = ["derive"] }
slab = "0.4.9"
thiserror = "2.0.0"
local-channel = "0.1.5"
webrtc-dtls = { version = "0.12.0", features = ["pem"] }
webrtc-util = "0.11.0"
rustls = { version = "0.23.12", default-features = false, features = [
    "std",
    "ring",
] }
rcgen = "0.13.1"
sha2 = "0.10.8"
notify = "8.2.0"
dirs = "6"
getrandom = "0.3"
same-file = "1.0.6"

[target.'cfg(unix)'.dependencies]
libc = "0.2.148"

[features]
default = [
    "slint-ui",
    "layer_shell_capture",
    "x11_capture",
    "libei_capture",
    "wlroots_emulation",
    "libei_emulation",
    "rdp_emulation",
    "x11_emulation",
]
slint-ui = ["dep:lan-mouse-ui"]

layer_shell_capture = ["input-capture/layer_shell"]
x11_capture = ["input-capture/x11"]
libei_capture = ["input-event/libei", "input-capture/libei"]
libei_emulation = ["input-event/libei", "input-emulation/libei"]
wlroots_emulation = ["input-emulation/wlroots"]
x11_emulation = ["input-emulation/x11"]
rdp_emulation = ["input-emulation/remote_desktop_portal"]

[package.metadata.bundle]
name = "Syntra"
icon = ["target/icon.icns", "lan-mouse-ui/ui/assets/shell/syntra.svg"]
identifier = "de.feschber.LanMouse"
deb_depends = [ "libgtk-4-1", "libx11-6", "libxtst6" ]
osx_info_plist_exts = ["build-aux/macos-lsui-element.plist"]
resources = ["target/menubar-template.png"]
