[package]
name = "lan-mouse-adapter-fuse"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[target.'cfg(target_os = "linux")'.dependencies]
base64 = "0.22"
fuser = { version = "0.14", default-features = false }
lan-mouse-adapter-api = { path = "../../lan-mouse-adapter-api", version = "0.1.0" }
lan-mouse-proto = { path = "../../lan-mouse-proto", version = "0.3.0" }
libc = "0.2"
parking_lot = "0.12"
percent-encoding = "2.3"
