mod adapter_manager;
mod capture;
pub mod capture_test;
pub mod client;
mod clipboard;
pub mod config;
mod connect;
mod crypto;
mod dns;
mod emulation;
pub mod emulation_test;
mod file_transfer;
mod listen;
pub mod service;
mod transfer_manager;
