mod adapter_manager;
mod capture;
pub mod capture_test;
pub mod client;
mod clipboard;
pub mod config;
mod connect;
mod crypto;
mod discovery;
mod dns;
mod emulation;
pub mod emulation_test;
mod file_transfer;
mod history;
mod history_sync;
mod listen;
mod manual_transfer;
mod peer_profile;
pub mod service;
mod transfer_manager;
